version: "3.8"
services:
  api:
    build: .
    container_name: api
    depends_on:
      db:
        condition: service_healthy
  db:
    image: percona/percona-server:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"

# Names for volume
volumes:
  my-db:
