version: "3.9"
services:
  db:
    image: percona/percona-server:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: library
    volumes:
      - my-db:/var/lib/mysql
  api:
    build: .
    depends_on:
      - db
    command: python3 db.py

# Names our volume
volumes:
  my-db:
# docker compose up
# docker compose down
# Accessing to the dashboard: http://localhost:32433/graph/login
